### PR TITLE
more broken test cases

### PR DESCRIPTION
**Pull request by tjmehta**

### CODE REVIEW

**Comment by tjmehta** [comment]
@fearphage, I am going to revert your changes. Unless you have any other ideas

**Comment by fearphage** [comment]
I can tell you that calling 0 functions will generally be faster than calling N functions (where n is a positive integer :stuck_out_tongue_winking_eye:). However, please feel free to revert as you see fit. It is your project. My PR was merely a suggestion.

## Fix?

``` js
return x * 1 === x && x % 1 === 0 && x > 0
```

## Explanation

``` js
// Is it a number?
return x * 1 === x 
  // Is it an integer?
  && x % 1 === 0 
  // Is it positive?
  && x > 0
;
```

**Comment by tjmehta** [comment]
fixes #9

**Comment by tjmehta** [comment]
@fearphage Thank you!

**Pull request merged**
