### PR TITLE
removed dependencies

### PR DESCRIPTION
**Pull request by cameroncooper**

### CODE REVIEW

**Comment by tjmehta** [comment]
Nice, passes all test. Can you explain how this works exactly? Thanks :+1:

**Comment by tjmehta** [comment]
Is this better than #2? Right now I am leaning towards #2

**Comment by cameroncooper** [comment]
#2 is good, just not readable for most people. Personally I'd go with that one.

**Comment by tjmehta** [comment]
Cool, I am going to pull it, but I have also asked him for an explanation to how it works. Fortunately, with the tests we know it works with all edge cases. Can you take a peek at the tests and let me know if you see anything missing?

**Pull request closed without merging**
